name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # test-local-chezmoi:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       runner:
  #         - ubuntu-24.04
  #         - ubuntu-24.04-arm
  #         - ubuntu-22.04
  #         - ubuntu-22.04-arm
  #         - ubuntu-20.04
  #         - windows-2025
  #         - windows-2022
  #         - windows-2019
  #         - macos-15
  #         - macos-14
  #         - macos-13
  #   runs-on: ${{ matrix.runner }}
  #   steps:
  #     - name: Install
  #       run: |
  #         sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin
  #         chezmoi init --apply aariam/dotfiles --verbose
  #     - name: Home Directory
  #       run: |
  #         tree -a $HOME
  test-local-manual:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - ubuntu-20.04
          - windows-2025
          - windows-2022
          - windows-2019
          - macos-15
          - macos-14
          - macos-13
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
      - name: Install
        run: |
          sh install.sh --verbose
      - name: Home Directory
        run: |
          tree -a $HOME