name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # test-local-chezmoi:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       runner:
  #         - ubuntu-24.04
  #         - ubuntu-24.04-arm
  #         - ubuntu-22.04
  #         - ubuntu-22.04-arm
  #         - ubuntu-20.04
  #         - windows-2025
  #         - windows-2022
  #         - windows-2019
  #         - macos-15
  #         - macos-14
  #         - macos-13
  #   runs-on: ${{ matrix.runner }}
  #   steps:
  #     - name: Install
  #       run: |
  #         sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin
  #         chezmoi init --apply aariam/dotfiles --verbose
  #     - name: Home Directory
  #       run: |
  #         tree -a $HOME
  test-local-manual:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - ubuntu-20.04
          - windows-2025
          - windows-2022
          - windows-2019
          - macos-15
          - macos-14
          - macos-13
    runs-on: ${{ matrix.runner }}
    steps:
        # Remove installed packages and files from the runner:
        # - https://github.com/actions/runner-images/issues/222
        # - https://github.com/actions/runner-images/issues/709
        # - https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
        # - https://github.com/actions/runner-images/issues/2875
        # - https://github.com/apache/flink/blob/3c31e646a8efc13943b33d012a70d748cf11cdbc/tools/azure-pipelines/free_disk_space.sh
        # - https://github.com/orgs/community/discussions/25678
      - name: Clean Runner
        if: runner.os == 'Linux'
        # - https://github.com/jlumbroso/free-disk-space/
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
      - name: Repository Checkout
        uses: actions/checkout@v4
      - name: Install
        run: |
          sh install.sh --verbose
      - name: Home Directory
        if: runner.os != 'Windows'
        run: |
          tree -a "$HOME"
      - name: Home Directory
        if: runner.os == 'Windows'
        run: |
          tree "$HOME" /f /a
